export const popularGoogleFonts = [
  "Roboto",
  "Open Sans",
  "Montserrat",
  "Lato",
  "Poppins",
  "Inter",
  "Nunito",
  "Playfair Display",
  "Merriweather",
  "Raleway",
  "PT Sans",
  "Lora",
  "Rubik",
  "Work Sans",
  "Arvo",
  "Noto Sans",
  "Nunito Sans",
  "Quicksand",
  "Fira Sans",
  "Hind",
  "Crimson Text",
  "Josefin Sans",
  "Libre Baskerville",
  "Anton",
  "Cabin",
  "Karla",
  "Inconsolata",
  "Signika",
  "Maven Pro",
  "Bitter",
  "Source Sans Pro",
  "Pacifico",
  "Shadows Into Light",
  "Indie Flower",
  "Dosis",
  "Oxygen",
  "Arimo",
  "Dancing Script",
  "Bebas Neue",
  "Abril Fatface",
  "Comfortaa",
  "Righteous",
  "Barlow",
  "Amatic SC",
  "Fredoka One",
  "Lobster",
  "Permanent Marker",
  "Satisfy",
  "Courgette",
  "Patua One",
  "Great Vibes",
  "Kaushan Script",
  "Sacramento",
  "Cookie",
  "Tangerine",
  "Monoton",
  "Press Start 2P"
].sort();
